export const PotentialScamsFilterList = [
    "dm me if interested",
    "giving away my",
    "i accidentally reported you",
    "it's still functional and in good shape",
    "ready for pickup",
    "free nitro",
    "discord nitro giveaway",
    "claim your nitro",
    "steam gift",
    "free steam gift",
    "gift card giveaway",
    "limited time offer",
    "claim your prize",
    "cashapp me",
    "cash app me",
    "congratulations you have won",
    "exclusive giveaway",
    "crypto giveaway",
    "double your crypto",
    "send and receive",
    "investment opportunity",
    "guaranteed returns",
    "100% profit",
    "risk free investment",
    "easy money",
    "earn money fast",
    "work from home and earn",
    "verify your account",
    "verify your identity",
    "confirm your account",
    "your account will be suspended",
    "click here to verify",
    "login to continue",
    "claim now",
    "act now",
    "expires today",
    "urgent action required",
    "message me privately",
    "contact me privately",
    "download this file",
    "download this game",
    "is this your account",
    "is this you",
    "did you report me",
    "help me recover my account",
    "vote for my team",
    "vote for my project",
    "vote for me",
    "can you vote",
    "need one more vote",
    "join this server",
    "join my server",
    "join via this link",
    "click this link",
    "open this link",
    "found your picture",
    "found your photos",
    "your photo is here",
    "claim your reward",
    "free robux",
    "free vbucks",
    "free cs2 skins",
    "free skins",
    "skin giveaway",
    "trade offer",
    "accept my trade",
    "verify your steam account",
    "contact support here",
    "wallet verification",
    "connect your wallet",
    "sign this transaction",
    "verify your wallet",
    "import your wallet",
    "wallet sync",
    "wallet upgrade",
    "mint now",
    "exclusive nft",
    "presale access",
    "whitelist spot",
    "claim whitelist",
    "instant withdrawal",
    "cash app flip",
    "money flip",
    "paypal flip",
    "cash giveaway",
    "send first",
    "trusted middleman",
    "escrow service",
    "gift inventory",
    "trade safely here",
    "verify ownership",
    "scan this qr code"
];